### ISSUE TITLE
Styles feedback

### ISSUE THREAD

**Issue by rarmatei** [MHDRateb/Homwork-1-#1]
Well done, Mohamad! Looks really good!

Here's my initial feedback for the styles, as I'm on my phone right now.

 Clean code:

I really like that you added comments in your css. It makes it easy for other developers read through your styles. You might want to spend some minutes to format your css rules a bit. For example, a CSS rule should look like this:
.myClass {
   background-color: blue;
}

But for some of your rules you have them in one line:
.myClass { background-color: blue; }

I think the first example is much more readable, so you can try converting your one line rules to spread to multiple lines.

Another thing you can do is indent your style rules properly. For example, the padding rule and the width rule below have different levels of indentation. So you can try to make them all the same so they line up properly.

ul.topnav {
    list-style-type: none;
    margin: 0;
    padding: 0;
  width:100%;
    overflow: visible;
    background-color: #52356B;
  float:left;
  font-size:2.5vw;
   border-color: #362544;
  border-width: 0px;
  border-style: solid;
  border-radius:50% ;
}

For font sizes, it's recommended that you use "em" units. Please try and Google "em css units" to read more about it and why it's recommended. In your styles, you're using "px" and "vw". "Vw" makes your font get bigger or smaller depending on the size of your browser window, and I'm not sure you want that? Try and see if you can use "em" everywhere.

//Background image copy locally
You are using an external image as your background. That is great! But you have to be careful about relying on external website for content, as the provider of that image might decide one day to delete his website, which will in turn brake yours as well. To solve this, you can try and copy that image in your own repository and load it locally.
See here for an example of how to do this:
http://stackoverflow.com/questions/14519388/can-i-use-an-image-from-my-local-file-system-as-background-in-html

Overall it looks very good, so keep up the great work!
Let me know if you didn't understand any of my comments, or if you disagree with any of them and I'll be happy to discuss!

**Comment by MohamadAlissa** [comment]
done,
Thanks for your feedback
